let vusarData = {
    title: "Vusar",
    date: "January 2019 - Current",
    projectSummary: 
    "   Vusar is a startup in the tech industry who is developing an app that will enable collaboration among engineers away from their computers and into the real, tangible world. I was brought in as an iOS Developer intern and have been since. This company has given me a learning oppurtunity into the world of iOS Development and it was my first experience in this field.\n\n\tI can't too much about the app as I am still under my NDA agreement however I may share some of what I have contributed to the team. My role on the team has varied, but it focuses a lot on building the features, as well as distribution of the builds to testers. I aided in the research and integration of loading in .usdz files from the user's database and into their Augmented Reality session. I also, contributed to User Interface of the Object Info Card. Lastly, I set up the Provisioning Profiles, as well as updating them with new testers. Along with this responsibility, I integrated fastlane to automate the deployment process.\n\n\tThis oppurtunity has given me a lot of insight into what it is like to be a developer. It not only taught me how to develop iOS Apps, but it also taught me other invaluable skills such as problem solving, how to be resourcefull to find the solution to problems, and communication with my team and through our frequent SCRUM meetings.\n\nCheck out our website to find out more about what we are doing here: https://www.vusar.co/"
};

let redAppleData = {
    title: "Red Apple",
    date: "Febuary 2019 - Current",
    projectSummary: 
    "\tRed Apple has given an oppurtunity to develop my skills in other areas of iOS Development that was not available to me at Vusar. As opposed to Vusar where I wrote a lot of code for the functionality of the app, at Red Apple I have spent more time in writing Unit Tests and User Interface tests as well as Research and Development.\n\n\tThe app we are developing here will help match patients with health-care providers, and vice-versa. We are using an algorigthm too find the best matches between the two parties and displays several results that fit the user's preferences. It takes into account preferences such as: distance, fee-range, and preferred insurance.\n\n\tAs stated before, I have contributed over 30+ Unit tests which serve to test the functionality of the endpoints of our AWS backend. I also, have written the User Interface tests to verify all flows for the messaging feature are functioning correctly. Lastly, I am doing research and development for possible improvements to the app. This internship is a great supplementary learning oppurtunity to my other internship to teach me various stages of iOS Application Development."
};

let personalWebsiteData = {
    title: "Personal Website",
    date: "July 2019 - Current",
    projectSummary: 
    "\tDuring the summer of 2019 I set out to learn new skills. My curiousity for other fields of computer science motivated me to learn web-development. I started off learning javascript through a Udemy Course. After completing that course, I completed the CSS and HTML Udemy course taught by the same instructor. These two courses taught me the basics of how to develop a website.\n\n\tAs I started developing I quickly realized that I did not know everything I needed to know to completely build a website from scratch. However, it did not stop me from moving forward as you can see. Using my resourcefulness I sought help from my greatest resource available to me, Google. Whenever I wanted to implement a feature and did not know where to start, I googled it and after many videos and stack overflow posts I was able to achieve many things the courses did not teach me. For instance, I wanted to animate my name banner with the vertical lines coming down that loads in when the page first loads. After a long time researching I came to the conclusion of using JQuery and .animate function to achieve this. This website is a testament to my resourcefullness and self-motivation."
};

let vgdcGameData = {
    title: "2D-Platformer",
    date: "September 2018 - December 2018",
    projectSummary:
    "This was my first project I commited extra-curricular time to completing. Along, with 5 other programmers, we completed a 2D-Platformer using the Unity Engine.\n\n\tHeading into this project I knew nothing about game-development and Unity, and I was not the only one. We were all beginners. I was voted to be the leader of the group, which as time passed grew to be a more difficult task. I was the one to lead the group in the learning stage where we all taught ourselves Unity. Along with this responsibility, I delegated out features and made sure these features were finished on time. If not, I would flex team-members to alleviate the blocker. It felt like an Agile Software Development process, but I did not know this at the time. Lastly, I managed the GitHub repo, resolving merge conflicts and approving pull requests.\n\n\tAs stated before, being that we were all beginners, it was difficult to learn and implement new things at the same time. But seeing the finished product and letting other people play it, made our success all that much more satisfying. This project really made me flex my leadership and communication skills, and it was a great learning opportunity for me to improve in these areas."
};
let dataObjects = [vusarData, redAppleData, personalWebsiteData, vgdcGameData];